### ISSUE TITLE
[BUG] Retention periods are being ignored by restic forget when "${extra_args[@]}" is empty

### ISSUE THREAD

**Issue by ggzica** [erikw/restic-automatic-backup-scheduler#120] opened 2023-09-02 17:50 UTC
When the variable  "${extra_args[@]}" is empty, the retention period options will be ignored and this warning will show up 

```shell
Ignoring "": multiple IDs with prefix "" found
Ignoring "filters": explicit snapshot ids are given
``` 

### I was able to solve my issue by removing the "${extra_args[@]}"  variable from restic forget in restic_backup.sh

```python
restic forget \
        --verbose="$RESTIC_VERBOSITY_LEVEL" \
        --tag "$RESTIC_BACKUP_TAG" \
        "${B2_ARG[@]}" \
        "${extra_args[@]}" \       <======== REMOVED THIS to solve my issue
        --prune \
        --group-by "paths,tags" \
        --keep-hourly "$RESTIC_RETENTION_HOURS" \
        --keep-daily "$RESTIC_RETENTION_DAYS" \
        --keep-weekly "$RESTIC_RETENTION_WEEKS" \
        --keep-monthly "$RESTIC_RETENTION_MONTHS" \
        --keep-yearly "$RESTIC_RETENTION_YEARS" &
wait $!
``` 

- OS: Ubuntu 22.04.2 LTS
- Restic Version: 0.16.0 compiled with go1.20.6 on linux/amd64

**Comment by erikw** [comment] 2023-09-05 20:46
Hey thanks for reporting this!

This was introduced recently in https://github.com/erikw/restic-automatic-backup-scheduler/pull/115

I currently am not able to look in to this. Maybe @nettnikl would have time to take a look possible? :)

**Comment by nettnikl** [comment] 2023-09-05 23:44
Sure thing! Might be caused by an empty array being used where we want nothing at all? @georgioghazzi could you put in the following right before the restic forget call?
```
/tmp/t.sh "${extra_args[@]}" 
```

And execute the following:
```
echo 'echo "args"; for arg in "$@"; do echo "> $arg"; done; echo "args/"' > /tmp/t.sh
chmod u+x /tmp/t.sh
```
Then check the diffs with an empty extra_args and one with some dummy arg?

**Comment by ggzica** [comment] 2023-09-10 13:48
Sorry for the late reply.
I've added /tmp/t.sh right before restic forget and i got the same result.


## Result Before adding /tmp/t.sh "${extra_args[@]}" 
![image](https://github.com/erikw/restic-automatic-backup-scheduler/assets/37176531/06466a64-6a5d-4f9b-963d-432a28c5ad17)

## /tmp/t.sh "${extra_args[@]}" added
![image](https://github.com/erikw/restic-automatic-backup-scheduler/assets/37176531/e27aa5fb-ae93-48a7-a67d-682302b13e52)

## Result After Adding /tmp/t.sh "${extra_args[@]}" 
![image](https://github.com/erikw/restic-automatic-backup-scheduler/assets/37176531/901b0253-9415-4f70-9df6-2718ee8d697a)

## Results Without  "${extra_args[@]}" variable in forget
![image](https://github.com/erikw/restic-automatic-backup-scheduler/assets/37176531/464ce1e6-c92b-4304-b281-20421e033b07)

**Comment by nettnikl** [comment] 2023-09-10 17:08
Thanks for your reply! Yeah i just meant to verify the issue - the extra args array is expanded to to " " when empty instead of to nothing. This seems to cause the restic commands to fail in case of positional arguments...
I'll have to think and try a bit more around how to fix.

**Comment by ggzica** [comment] 2023-09-10 17:26
I moved the location of the ${extra_args} to the end of the forget command, but that did not solve the issue.
Thanks for your script btw!

**Comment by nettnikl** [comment] 2023-09-10 18:25
Okay, so from my tests it seems the only way is to remove the quotes... as with the read command we already took care of input validation etc. (please confirm or explain @erikw if possible) - we maybe could leave them out here?

**Comment by erikw** [comment] 2023-09-25 16:36
I took the decision to revert #115 with 2873f6a31592ba8e40666cc53bace2d27cf2408d because I don't have time to look at a fix for this right now, and the change as not included in a new release yet.

I'm open to add the functionality of #115 again, if it works out of the box without this bug :)

**Closed by erikw** 2023-09-25 16:36 UTC
